import { Dimensions, StyleSheet } from "react-native";

export default {
    radius: Dimensions.get('window').width * 0.015,
    screenWidth: Dimensions.get('window').width,
    screenHeight: Dimensions.get('window').height,
    screenPadding: Dimensions.get('window').width * 0.05,
    fontSize: {
        "text-xs": 12,
        "text-sm": 14,
        "text-base": 16,
        "text-lg": 18,
        "text-xl": 20,
        "text-2xl": 24,
        "text-3xl": 30,
        "text-4xl": 36,
        "text-5xl": 48,
        "text-6xl": 60,
        "text-7xl": 72,
        "text-8xl": 96,
        "text-9xl": 28,
    },
    background: "#f0f0f0",
    foreground: "#09090b",
    card: "#ffffff",
    cardForeground: "#09090b",
    popover: "#ffffff",
    popoverForeground: "#09090b",
    primary: "#fb2c36",
    primaryLight: "#FED5D7",
    primaryForeground: "#fef2f2",
    secondary: "#f4f4f5",
    secondaryForeground: "#18181b",
    muted: "#f4f4f5",
    mutedForeground: "#71717b",
    accent: "#f4f4f5",
    accentForeground: "#18181b",
    destructive: "#e7000b",
    border: "#e4e4e7",
    input: "#e4e4e7",
    ring: "#fb2c36",
    chart1: "#f54a00",
    chart2: "#009689",
    chart3: "#104e64",
    chart4: "#ffba00",
    chart5: "#fd9a00",
    sidebar: "#fafafa",
    sidebarForeground: "#09090b",
    sidebarPrimary: "#fb2c36",
    sidebarPrimaryForeground: "#fef2f2",
    sidebarAccent: "#f4f4f5",
    sidebarAccentForeground: "#18181b",
    sidebarBorder: "#e4e4e7",
    sidebarRing: "#fb2c36",
    dark: {
        background: "#09090b",
        foreground: "#fafafa",
        card: "#18181b",
        cardForeground: "#fafafa",
        popover: "#18181b",
        popoverForeground: "#fafafa",
        primary: "#fb2c36",
        primaryForeground: "#fef2f2",
        secondary: "#27272a",
        secondaryForeground: "#fafafa",
        muted: "#27272a",
        mutedForeground: "#9f9fa9",
        accent: "#27272a",
        accentForeground: "#fafafa",
        destructive: "#ff6467",
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.15)",
        ring: "#fb2c36",
        chart1: "#1447e6",
        chart2: "#00bc7d",
        chart3: "#fd9a00",
        chart4: "#ad46ff",
        chart5: "#ff2056",
        sidebar: "#18181b",
        sidebarForeground: "#fafafa",
        sidebarPrimary: "#fb2c36",
        sidebarPrimaryForeground: "#fef2f2",
        sidebarAccent: "#27272a",
        sidebarAccentForeground: "#fafafa",
        sidebarBorder: "rgba(255, 255, 255, 0.1)",
        sidebarRing: "#fb2c36",
    },
    styles: StyleSheet.create({
        justifyCen_AlignCen: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
        }
    }),
    customColor: {
        discount: "#CC0C39"
    }
}